In [1]:
import numpy as np
array1=[[11,12,13],
       [14,15,16],
       [17,18,19]]
array1_new=np.array(array1)
print(array1)

[[11, 12, 13], [14, 15, 16], [17, 18, 19]]


In [2]:
print(array1_new)

[[11 12 13]
 [14 15 16]
 [17 18 19]]


In [4]:
x=[1,2,3,4]
array2=np.array(x)
print(array2)

[1 2 3 4]


In [6]:
import numpy as np
my_list=[[1,2,3],
        [4,5,6]]
array3=np.array(my_list,dtype=np.int)
print(array3)

[[1 2 3]
 [4 5 6]]


In [6]:
##shape and ndim

In [10]:
import numpy as np
array1=[[11,12,13],
       [14,15,16],
       [17,18,19]]
array1_new=np.array(array1)


In [12]:
print(array1_new.ndim)

2


In [13]:
x=[1,2,3,4]
array2=np.array(x)
print(array2.ndim)

1


In [14]:
print(array1_new.shape)

(3, 3)


In [15]:
##np.arrange() and np.resize()

In [16]:
print(array1_new)

[[11 12 13]
 [14 15 16]
 [17 18 19]]


In [18]:
array2=array1_new.reshape(3,3)
print(array2)

[[11 12 13]
 [14 15 16]
 [17 18 19]]


In [25]:
array=np.arange(-10,10,2)
print(array)

[-10  -8  -6  -4  -2   0   2   4   6   8]
