In [1]:
import numpy as np
array1=[[11,12,13],
       [14,15,16],
       [17,18,19]]
array1_new=np.array(array1)
print(array1)

[[11, 12, 13], [14, 15, 16], [17, 18, 19]]


In [2]:
print(array1_new)

[[11 12 13]
 [14 15 16]
 [17 18 19]]


In [4]:
x=[1,2,3,4]
array2=np.array(x)
print(array2)

[1 2 3 4]


In [6]:
import numpy as np
my_list=[[1,2,3],
        [4,5,6]]
array3=np.array(my_list,dtype=np.int)
print(array3)

[[1 2 3]
 [4 5 6]]


In [ ]:
##shape and ndim