In [1]:
import numpy as np
array1=[[11,12,13],
       [14,15,16],
       [17,18,19]]
array1_new=np.array(array1)
print(array1)

[[11, 12, 13], [14, 15, 16], [17, 18, 19]]


In [2]:
print(array1_new)

[[11 12 13]
 [14 15 16]
 [17 18 19]]


In [4]:
x=[1,2,3,4]
array2=np.array(x)
print(array2)

[1 2 3 4]


In [6]:
import numpy as np
my_list=[[1,2,3],
        [4,5,6]]
array3=np.array(my_list,dtype=np.int)
print(array3)

[[1 2 3]
 [4 5 6]]


In [6]:
##shape and ndim

In [10]:
import numpy as np
array1=[[11,12,13],
       [14,15,16],
       [17,18,19]]
array1_new=np.array(array1)


In [12]:
print(array1_new.ndim)

2


In [13]:
x=[1,2,3,4]
array2=np.array(x)
print(array2.ndim)

1


In [14]:
print(array1_new.shape)

(3, 3)


In [15]:
##np.arrange() and np.resize()

In [16]:
print(array1_new)

[[11 12 13]
 [14 15 16]
 [17 18 19]]


In [18]:
array2=array1_new.reshape(3,3)
print(array2)

[[11 12 13]
 [14 15 16]
 [17 18 19]]


In [25]:
array=np.arange(-10,10,2)
print(array)

[-10  -8  -6  -4  -2   0   2   4   6   8]


In [1]:
##array Creation Routines

In [4]:
import numpy as np
x=np.empty((3,2),dtype=np.int)
print(x)

[[6553710 3342433]
 [4980828 6422633]
 [6357106 7929970]]


In [5]:
x=np.zeros(5)
print(x)

[0. 0. 0. 0. 0.]


In [9]:
x=np.zeros((3,2),dtype=np.float)
print(x)

[[0. 0.]
 [0. 0.]
 [0. 0.]]


In [13]:
x=np.ones((3,2),dtype=np.int)
print(x)

[[1 1]
 [1 1]
 [1 1]]


In [15]:
x=np.zeros((3,2),dtype=np.int)
print(x)

[[0 0]
 [0 0]
 [0 0]]


In [16]:
##indexing and Slicing

In [18]:
array=np.random.randint(0,100,(10,5))
print(array)

[[17 86  5 40 42]
 [ 7 42 15  1 67]
 [ 0 36 72 14 30]
 [32 90 27 26 57]
 [20 70 39 82 94]
 [86 69 41 91  3]
 [56 45 51 24 25]
 [13 24 67 88 77]
 [23 78 36 19 73]
 [88 63 32 75 42]]


In [20]:
array1=np.random.randint(0,100,(4,3))
array2=np.random.randint(0,100,(4,3))
array3=array1+array2
print('array1:',array1)
print('array2:',array2)
print('array3:',array3)

array1: [[52 76 81]
 [24  5 12]
 [73 39 17]
 [86 97 90]]
array2: [[30 18 10]
 [80 23 35]
 [29 97 17]
 [43 33 71]]
array3: [[ 82  94  91]
 [104  28  47]
 [102 136  34]
 [129 130 161]]


In [21]:
array1=np.random.randint(0,100,(4,3))
array2=array1/10
print('array1:',array1)
print('array2:',array2)

array1: [[47 97 36]
 [93 95 16]
 [67 10 95]
 [92 33 91]]
array2: [[4.7 9.7 3.6]
 [9.3 9.5 1.6]
 [6.7 1.  9.5]
 [9.2 3.3 9.1]]


In [22]:
array1=np.random.randint(0,100,(4,3))
array2=np.random.randint(0,100,(3,5))
print('array1:',array1)
print('array2:',array2)
array4=np.matmul(array1,array2)
print('Mautipication',array4)

array1: [[ 4 12 22]
 [43 20 78]
 [48 92 48]
 [60 94 74]]
array2: [[48  2 34  1 27]
 [52 27 87 48 98]
 [88 80 99 89 30]]
Mautipication [[ 2752  2092  3358  2538  1944]
 [ 9968  6866 10924  7945  5461]
 [11312  6420 14388  8736 11752]
 [14280  8578 17544 11158 13052]]
