In [1]:
import numpy as np
array1=[[11,12,13],
       [14,15,16],
       [17,18,19]]
array1_new=np.array(array1)
print(array1)

[[11, 12, 13], [14, 15, 16], [17, 18, 19]]


In [2]:
print(array1_new)

[[11 12 13]
 [14 15 16]
 [17 18 19]]


In [4]:
x=[1,2,3,4]
array2=np.array(x)
print(array2)

[1 2 3 4]


In [2]:
import numpy as np
my_list=[[1,2,3],
        [4,5,6]]
array3=np.array(my_list,dtype=np.int)
print(array3)

[[1 2 3]
 [4 5 6]]


In [3]:
##shape and ndim

In [4]:
import numpy as np
array1=[[11,12,13],
       [14,15,16],
       [17,18,19]]
array1_new=np.array(array1)


In [5]:
print(array1_new.ndim)

2


In [6]:
x=[1,2,3,4]
array2=np.array(x)
print(array2.ndim)

1


In [7]:
print(array1_new.shape)

(3, 3)


In [8]:
##np.arrange() and np.resize()

In [9]:
print(array1_new)

[[11 12 13]
 [14 15 16]
 [17 18 19]]


In [10]:
array2=array1_new.reshape(3,3)
print(array2)

[[11 12 13]
 [14 15 16]
 [17 18 19]]


In [11]:
array=np.arange(-10,10,2)
print(array)

[-10  -8  -6  -4  -2   0   2   4   6   8]


In [12]:
##array Creation Routines

In [13]:
import numpy as np
x=np.empty((3,2),dtype=np.int)
print(x)

[[1033525392        507]
 [         0          0]
 [    131074    3539031]]


In [14]:
x=np.zeros(5)
print(x)

[0. 0. 0. 0. 0.]


In [15]:
x=np.zeros((3,2),dtype=np.float)
print(x)

[[0. 0.]
 [0. 0.]
 [0. 0.]]


In [16]:
x=np.ones((3,2),dtype=np.int)
print(x)

[[1 1]
 [1 1]
 [1 1]]


In [17]:
x=np.zeros((3,2),dtype=np.int)
print(x)

[[0 0]
 [0 0]
 [0 0]]


In [18]:
##indexing and Slicing

In [19]:
array=np.random.randint(0,100,(10,5))
print(array)

[[86 64 29 21 36]
 [ 9 72 80 54 31]
 [99 38 89 96 28]
 [38 66 85 34  7]
 [51 37 14 94  2]
 [21 62 17 36 68]
 [94 99 18 19 66]
 [17 29 74 33 66]
 [ 6 40 16 50 99]
 [50  9  2  6 79]]


In [20]:
array1=np.random.randint(0,100,(4,3))
array2=np.random.randint(0,100,(4,3))
array3=array1+array2
print('array1:',array1)
print('array2:',array2)
print('array3:',array3)

array1: [[71 96 76]
 [42  0 34]
 [97 66 93]
 [98 30 12]]
array2: [[56 77 99]
 [85  2  7]
 [49 76 99]
 [95 26 24]]
array3: [[127 173 175]
 [127   2  41]
 [146 142 192]
 [193  56  36]]


In [21]:
array1=np.random.randint(0,100,(4,3))
array2=array1/10
print('array1:',array1)
print('array2:',array2)

array1: [[24 45  9]
 [46  4 50]
 [ 2 25 18]
 [38  5  9]]
array2: [[2.4 4.5 0.9]
 [4.6 0.4 5. ]
 [0.2 2.5 1.8]
 [3.8 0.5 0.9]]


In [22]:
array1=np.random.randint(0,100,(4,3))
array2=np.random.randint(0,100,(3,5))
print('array1:',array1)
print('array2:',array2)
array4=np.matmul(array1,array2)
print('Mautipication',array4)

array1: [[42  9 45]
 [56 37 22]
 [87 84 49]
 [46 15  7]]
array2: [[56 72 66 72 16]
 [21 71 66 35 65]
 [53 10  4 54 95]]
Mautipication [[ 4926  4113  3546  5769  5532]
 [ 5079  6879  6226  6515  5391]
 [ 9233 12718 11482 11850 11507]
 [ 3262  4447  4054  4215  2376]]


In [23]:
array=np.random.randint(0,100,(5,7))
print(array)

[[ 9 78 63 68 63 28 55]
 [42 30 49 45 55 22 98]
 [32 33 42 74 26 44  5]
 [59 72 24 30  9  2 68]
 [22 26 50  5 11 34 59]]


In [24]:
print(np.max(array))

98


In [29]:
print(np.mean(array))

40.91428571428571


In [30]:
print(np.argmax(array)) #the index of max value

13


In [31]:
print(np.max(array,axis=0)) ##go to axis=0 and get max value in each column(x axis)

[59 78 63 74 63 44 98]


In [27]:
print(np.argmax(array,axis=0)) ##give index of each column value

[3 0 0 2 0 2 1]


In [32]:
array=np.random.randint(0,100, (5,10))
print(array)

[[ 6 63 33 56 40 11 93 22 70 32]
 [36 27 15 58  4 15 89 81 13  9]
 [94  1 30 17 16 28 30 19 90  5]
 [69 32 22 44 33 11 73  6 30 66]
 [45 61 15 10 20 98  3 95 32 23]]


In [33]:
print(array[0:2,0:4]) ##row wise go to 2nd and column wise go to 4

[[ 6 63 33 56]
 [36 27 15 58]]


In [34]:
print(array[:,0:4])

[[ 6 63 33 56]
 [36 27 15 58]
 [94  1 30 17]
 [69 32 22 44]
 [45 61 15 10]]


In [35]:
print(array[:,4]) #all rows and fouce on only 4th column

[40  4 16 33 20]


In [36]:
print(array[:2,:])

[[ 6 63 33 56 40 11 93 22 70 32]
 [36 27 15 58  4 15 89 81 13  9]]


In [39]:
avg=np.mean(array[:2,:])
print(avg)

38.65


In [50]:
import pandas as pd

In [51]:
dataset=pd.read_csv('student_marks.csv')
print(dataset)

  Unnamed: 0 Gender         DOB  Maths  Physics  Chemistry  English  Biology  \
0       John      M  05/04/1988     55       45       56.0       87       21   
1     Suresh      M    4/5/1987     75       55        NaN       64       90   
2     Ramesh      M   25/5/1989     25       54       89.0       76       95   
3    Jessica      F   12/8/1990     78       55       86.0       63       54   
4   Jennifer      F    2/9/1989     58       96       78.0       46       96   

   Economics  History  Civics  
0         52       89      65  
1         61       58       2  
2         87       56      74  
3         89       75      45  
4         77       83      53  


In [52]:
dataset=pd.read_csv('student_marks.csv').values
print(dataset)


[['John' 'M' '05/04/1988' 55 45 56.0 87 21 52 89 65]
 ['Suresh' 'M' '4/5/1987' 75 55 nan 64 90 61 58 2]
 ['Ramesh' 'M' '25/5/1989' 25 54 89.0 76 95 87 56 74]
 ['Jessica' 'F' '12/8/1990' 78 55 86.0 63 54 89 75 45]
 ['Jennifer' 'F' '2/9/1989' 58 96 78.0 46 96 77 83 53]]


In [53]:
import numpy as np
avg=np.mean(dataset[:,1:],axis=0)
print(avg)

TypeError: unsupported operand type(s) for /: 'str' and 'int'